### ISSUE TITLE
Could you give me the datasets in convenience?

### ISSUE THREAD

**Issue by songwenshuang** [Peter554/BACH#3]
Because I need to join  with the project  as a participant,then I can download the dataset .But the project has been closed! So could you give me the datasets in convenience?
Thanks a lot !

**Comment by Peter554** [comment]
I'm not sure I'm allowed to distribute the dataset sorry. You may well be able to get it from the challenge website: https://iciar2018-challenge.grand-challenge.org/, even if the official challenge is finished. Perhaps contact the challenge organizers if having trouble?
