### ISSUE TITLE
Can you explain how CNN evaluate majrity voting

### ISSUE THREAD

**Issue by imairish** [Peter554/BACH#4]
I am unable to understand how keras CNN evaluating the classification for each whole image by majority voting as there is nowhere no. of patches per images given . can you please explain how majority voting works in keras

**Comment by Peter554** [comment]
You are quite correct! The CNN does indeed only classify patches. To classify the full images you will need to write another script to do the majority voting over patches as you say.

**Comment by imairish** [comment]
Thanks for the quick response. so how would i know the classification of each patch and if we shuffle patches during training then how i get the patches of an image?

**Comment by imairish** [comment]
or is there anyway in keras to give the whole image and it divide the image into patches by itself like data augmentation. I searched a lot in keras documentation but didn't found any method for this may be i missed it.

**Comment by Peter554** [comment]
There is no way to do this in keras true. You should separate mentally the two parts of the process: 1) Training a patch based classifier 2) Predicting labels on new, full images. The (not maintained) code in this repo may help with 1). For part 2) you must subdivide the image yourself, classify all patches individually using CNN of part 1) and then majority vote for full image. This (not tested) may help:

```python
image = ... # Read the image into numpy array RGB uint8 
ps = 512 # Patchsize
patches = []
for i in range(3):
    for j in range(4):
        patch = image[ps * i : ps * (i + 1), ps * j : ps * (j + 1)]
        patches.append(patch)
```

**Comment by imairish** [comment]
Thanks for your help!
